# Generated by Django 5.2.13 on 2026-04-22 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_expanded_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admitcard',
            options={'ordering': ['-admit_card_date']},
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'ordering': ['-exam_year', '-result_date']},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-application_end_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['-exam_year'], 'verbose_name_plural': 'Syllabi'},
        ),
        migrations.RenameIndex(
            model_name='jobposting',
            new_name='content_job_state_i_21930a_idx',
            old_name='content_job_state_created_idx',
        ),
        migrations.RenameIndex(
            model_name='jobposting',
            new_name='content_job_organiz_750fce_idx',
            old_name='content_job_org_created_idx',
        ),
        migrations.RenameIndex(
            model_name='jobposting',
            new_name='content_job_exam_ca_4c40c5_idx',
            old_name='content_job_cat_created_idx',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='download_link',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='download_link',
        ),
        migrations.AlterField(
            model_name='admitcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='admitcard',
            name='download_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='admitcard',
            name='exam_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2026, 4, 22, 7, 44, 6, 901140, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='result_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='application_end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='application_start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
