# Generated by Django 5.2.13 on 2026-04-22 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_admitcard_options_alter_examresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateverification',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='BoardExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('CBSE', 'Central Board of Secondary Education'), ('ICSE', 'Indian Certificate of Secondary Education'), ('UP Board', 'Uttar Pradesh Board'), ('Bihar Board', 'Bihar School Examination Board'), ('MP Board', 'Madhya Pradesh Board'), ('Rajasthan Board', 'Rajasthan Board of Secondary Education'), ('Haryana Board', 'Haryana Board of School Education'), ('Punjab Board', 'Punjab School Education Board'), ('Gujarat Board', 'Gujarat Secondary and Higher Secondary Education Board'), ('Maharashtra Board', 'Maharashtra State Board of Secondary and Higher Secondary Education')], max_length=20)),
                ('exam_type', models.CharField(choices=[('10th', 'Class 10th'), ('12th', 'Class 12th')], max_length=10)),
                ('year', models.IntegerField()),
                ('result_link', models.URLField(help_text='Direct link to board result website')),
                ('digilocker_link', models.URLField(blank=True, help_text='DigiLocker verification link')),
                ('result_date', models.DateField()),
                ('is_declared', models.BooleanField(default=False)),
                ('total_students', models.PositiveIntegerField(blank=True, null=True)),
                ('pass_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-result_date'],
                'unique_together': {('board', 'exam_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ImportantNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('Government', 'Government Notification'), ('Exam', 'Exam Notification'), ('Admission', 'Admission Notification'), ('Recruitment', 'Recruitment Notification'), ('Policy', 'Policy Update'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('notification_link', models.URLField(blank=True)),
                ('pdf_link', models.URLField(blank=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.organization')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.state')),
            ],
            options={
                'ordering': ['-is_urgent', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='OnlineForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('Job Application', 'Job Application'), ('Admission', 'Admission Form'), ('Certificate', 'Certificate Application'), ('License', 'License Application'), ('Scholarship', 'Scholarship Application'), ('Other', 'Other')], max_length=50)),
                ('form_link', models.URLField()),
                ('application_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('eligibility', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Extended', 'Extended')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.organization')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.state')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('SC/ST', 'SC/ST Scholarship'), ('OBC', 'OBC Scholarship'), ('Minority', 'Minority Scholarship'), ('Merit', 'Merit Scholarship'), ('General', 'General Scholarship')], max_length=20)),
                ('application_start_date', models.DateField()),
                ('application_end_date', models.DateField()),
                ('application_link', models.URLField()),
                ('eligibility', models.TextField()),
                ('benefits', models.TextField()),
                ('documents_required', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Coming Soon', 'Coming Soon')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.state')),
            ],
            options={
                'ordering': ['-application_end_date'],
            },
        ),
    ]
