# Generated by Django 5.2.13 on 2026-04-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_certificateverification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='year',
            field=models.IntegerField(db_index=True, default=2024, help_text='Recruitment year (e.g., 2026)'),
            preserve_default=False,
        ),
    ]
