# Generated by Django 5.2.13 on 2026-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_jobposting_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-year', '-application_end_date', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['year', '-application_end_date'], name='content_job_year_696e5e_idx'),
        ),
    ]
