# Generated by Django 5.2.13 on 2026-05-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_jobposting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcard',
            name='exam_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='exam_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
