# Generated by Django 5.2.13 on 2026-05-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('eligibility', 'Eligibility & Requirements'), ('application', 'Application Process'), ('exams', 'Exams & Selection'), ('age', 'Age & Category Relaxation'), ('documents', 'Documents & Verification'), ('salary', 'Salary & Benefits'), ('career', 'Career Growth'), ('other', 'Other')], db_index=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order'],
            },
        ),
    ]
