# Generated by Django 5.2.13 on 2026-05-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_bio',
            field=models.CharField(default='Specialist in government job guidance with 8+ years of experience', help_text='Author bio for byline', max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='author_credentials',
            field=models.CharField(default='Career Counselor, Government Job Expert', help_text='Author expertise/credentials', max_length=150),
        ),
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(default='Sarkari Naukri Editor', help_text='Author name for byline', max_length=100),
        ),
    ]
